name: messio
description: Messio is a modern messaging app

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  rubber: ^0.3.2
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"
  adaptive_icon_foreground: "assets/launcher/ic_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
