name: messio
description: Messio is a modern messaging app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  rubber: ^0.3.2
  cupertino_icons: ^0.1.2
  infinite_listview: ^1.0.0
  firebase_auth: ^0.15.5+3 #to auth with firebase
  google_sign_in: ^4.4.0 #to auth with google account
  flutter_bloc: ^0.21.0 #helps in implementing blocs
  equatable: ^0.5.0 #helps in comparing class using their values
  cloud_firestore: ^0.13.4+2 #Firebase Database
  image_picker: ^0.6.1+4 #image picker used for picking images from gallery
  firebase_storage: ^3.1.5 #storage for storing image files
  flutter_launcher_icons: ^0.7.2+1
  shared_preferences: ^0.5.3+4
  file_picker: ^1.4.0+1
  emoji_picker: ^0.0.2
  video_player: ^0.10.2+1
  flutter_downloader: ^1.2.2
  downloads_path_provider: ^0.1.0
  flushbar: 1.6.0
  path_provider: ^1.3.0
  cached_network_image: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  test: ^1.5.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"
  adaptive_icon_foreground: "assets/launcher/ic_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/launcher/
    - assets/fonts/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope-regular.otf
        - asset: assets/fonts/manrope-bold.otf
          weight: 700
        - asset: assets/fonts/manrope-extrabold.otf
          weight: 800
        - asset: assets/fonts/manrope-semibold.otf
          weight: 400
