name: messio
description: Messio is a modern messaging app

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  rubber: ^0.3.2
  cupertino_icons: ^0.1.2
  infinite_listview: ^1.0.0
  firebase_auth: ^0.14.0+4 #to auth with firebase
  google_sign_in: ^4.0.7 #to auth with google account
  flutter_bloc: ^0.21.0 #helps in implementing blocs
  equatable: ^0.5.0 #helps in comparing class using their values
  cloud_firestore: ^0.12.9+1 #Firebase Database
  image_picker: ^0.6.1+4 #image picker used for picking images from gallery
  firebase_storage: ^3.0.6 #storage for storing image files
  flutter_launcher_icons: ^0.7.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0
  test: ^1.5.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ic_launcher.png"
  image_path_android: "assets/launcher/ic_launcher.png"
  adaptive_icon_background: "assets/launcher/ic_background.png"
  adaptive_icon_foreground: "assets/launcher/ic_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/launcher/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
